apiVersion: v1
kind: Service
metadata:
  name: spring-starbucks-api-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 85
      targetPort: 5000
    - port: 1936
      targetPort: 1936
  selector:
    name: spring-starbucks-api
