# docker-compose up --scale cashier=2 -d
version: "3"

services:
  redis:
    image: redis
    platform: linux/amd64
    networks:
      - network
    ports:
      - 6379
    hostname: cmpe172cashier
    restart: always   
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - /tmp:/tmp
    networks:
      - network
    ports:
      - 3306
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD: "cmpe172"
    restart: always
  cashier:
    image: spring-cashier
    platform: linux/amd64
    depends_on:
      - mysql
    volumes:
      - /tmp:/tmp
    networks:
      - network
    ports:
      - 8080
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "happy"
      MYSQL_PASS: "camper"
      REDIS_HOST: "cmpe172cashier"
      REDIS_PASSWORD: "foobared"
    restart: always
  lb:
    image: eeacms/haproxy
    platform: linux/amd64
    depends_on:
      - cashier
    ports:
      - "80:5000"
      - "1936:1936"
    environment:
      BACKENDS: "cashier"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "false"
      LOG_LEVEL: "info"
    networks:
      - network

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge
